In [1]:
import tensorflow
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
import glob
import os
from PIL import Image
import cv2
import numpy as np
import matplotlib.pyplot as plt
import keras
import pandas as pd
from sklearn.model_selection import train_test_split


/home/javier/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/javier/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/javier/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/javier/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: 

In [11]:
carpeta = ["cubism_128/","expressionism_128/","fauvism_128_espejo/","pointillism_126_espejo/","pop_art_128_espejo/",'ukiyo_128']

In [12]:

def obtener_Ruta(carpeta):
    first = 'Inputs/imagenes_extraidas/128x128/'
    last = '*.jpg'
    result = first + carpeta + last
    return result


In [13]:
obtener_Ruta('expressionism_128/')

'Inputs/imagenes_extraidas/128x128/expressionism_128/*.jpg'

In [14]:
diccionario = {'cubism_128/': 1,
               'expressionism_128/':2,
               "fauvism_128_espejo/":3,
               "pointillism_126_espejo/":4,
               "pop_art_128_espejo/":5,
               'ukiyo_128/':6            
               }

def sacar_Imagenes(carpeta):
    lista = []
    for x in glob.glob(obtener_Ruta(carpeta)):
        for k,v in diccionario.items():
            if k in x:
                lista.append(v)
    return lista

In [16]:
z = []

for x in diccionario:
    z.append(sacar_Imagenes(x))
z

[[1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,


In [21]:
array = []
for x in z:
    array.append(np.asarray(x, dtype = np.int64))
array

[array([1, 1, 1, ..., 1, 1, 1]),
 array([2, 2, 2, ..., 2, 2, 2]),
 array([3, 3, 3, ..., 3, 3, 3]),
 array([4, 4, 4, ..., 4, 4, 4]),
 array([5, 5, 5, ..., 5, 5, 5]),
 array([6, 6, 6, ..., 6, 6, 6])]

In [26]:
y = np.concatenate((array[0],array[1],array[2],array[3],array[4],array[5]),axis = 0)
print(len(y))
print(y.shape)

9351
(9351,)


In [13]:
im = [] 
for file in glob.glob('Inputs/imagenes_extraidas/128x128/*/*.jpg'):
    im.append(cv2.imread(file)/255)
    
    

In [ ]:
X =np.asarray(im)

In [ ]:
X.shape

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, array_y, test_size=0.2)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

In [ ]:
from keras.utils import to_categorical
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

In [ ]:
num_classes = 6
input_shape = (128, 128, 3)

In [ ]:
#NN topology

model = Sequential()
inputShape = (128, 128, 3)
chanDim = -1
if K.image_data_format() == "channels_first":
    chanDim = 1
model.add(Conv2D(32, (3, 3), padding="same", input_shape=inputShape))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=chanDim))
model.add(MaxPooling2D(pool_size=(3, 3)))
model.add(Dropout(0.25))
model.add(Conv2D(64, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=chanDim))
model.add(Conv2D(64, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=chanDim))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(128, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=chanDim))
model.add(Conv2D(128, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=chanDim))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(1024))
model.add(Activation("relu"))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation("softmax"))
model.summary()
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

In [ ]:
batch_size = 100
epochs = 25

model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(X_test, y_test))

In [1]:
foto_expressionism =Image.open('/content/colab/imagenes_extraidas/pop_art_128_espejo/5264.jpg')
foto_expressionism

NameError: name 'Image' is not defined

In [ ]:
pred = model.predict(np.expand_dims(foto_expressionism,axis=0))[0]
pred